// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkbQc1wHeY8i-TJ0pZlunDeTywB1OmySk',
    appId: '1:466854985428:web:e6c18a6a177c809466c541',
    messagingSenderId: '466854985428',
    projectId: 'blood-bank-5264a',
    authDomain: 'blood-bank-5264a.firebaseapp.com',
    storageBucket: 'blood-bank-5264a.firebasestorage.app',
    measurementId: 'G-YW3VKFD8K5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_Cyw6buU04jwKDIvRCxv9exkCyEM0-qs',
    appId: '1:466854985428:android:9a2001c5f3a3e94c66c541',
    messagingSenderId: '466854985428',
    projectId: 'blood-bank-5264a',
    storageBucket: 'blood-bank-5264a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYB9kgSWC4HrBX3ELdRE5hr78DqC8exhQ',
    appId: '1:466854985428:ios:730738253ad0986e66c541',
    messagingSenderId: '466854985428',
    projectId: 'blood-bank-5264a',
    storageBucket: 'blood-bank-5264a.firebasestorage.app',
    iosBundleId: 'com.example.bloodbankDonors',
  );
}
